### ISSUE TITLE
Error in edit-global-article call

### ISSUE THREAD

**Issue by neelsomani** [akeshavan/brainspell-neo-frontend#31]
On the view-article page, after adding an article to a collection and saving changes, the request to update the global article information is malformed:

<img width="1078" alt="screen shot 2018-06-09 at 18 21 59" src="https://user-images.githubusercontent.com/7029855/41197406-400638b4-6c12-11e8-95b6-4be12532b937.png">

I think the data is being sent improperly. Here's the error I see:

<img width="545" alt="screen shot 2018-06-09 at 18 22 26" src="https://user-images.githubusercontent.com/7029855/41197407-4f9880f2-6c12-11e8-9f71-1d53984d6c24.png">

Here's the documentation for edit-global-article: https://brainspell.herokuapp.com/json/v2/edit-global-article/help

**Comment by Sharabesh** [comment]
Should have been resolved by [PR:#44](https://github.com/akeshavan/brainspell-neo-frontend/pull/44)
