### ISSUE TITLE
Footer too intrusive / big

### ISSUE THREAD

**Issue by neelsomani** [akeshavan/brainspell-neo-frontend#36]
Hey, I think the footer is a great idea. I think it might be covering a bit of information, though, particularly on the front page.

<img width="1280" alt="screen shot 2018-10-19 at 16 32 44" src="https://user-images.githubusercontent.com/7029855/47248101-fdca3500-d3bc-11e8-89d9-ebe625a9afed.png">

Maybe we could have it at the very bottom of every page, instead of floating at the bottom of the browser window.

**Comment by 62442katieb** [comment]
Yeah, I’ll work on it.

Katie

**Comment by 62442katieb** [comment]
Fixed!

**Comment by neelsomani** [comment]
I think the footer gets a bit stuck in the middle of the page when the page is longer than the screen size:

<img width="1104" alt="screen shot 2018-10-25 at 16 15 45" src="https://user-images.githubusercontent.com/7029855/47535655-52fcbf80-d871-11e8-99c0-ac99def0e935.png">

Maybe something like rearranging the footer div so it's at the bottom, and changing it to `position: relative` would be the best idea:

<img width="989" alt="screen shot 2018-10-25 at 16 15 34" src="https://user-images.githubusercontent.com/7029855/47535675-627c0880-d871-11e8-8590-af64f24e9ad9.png">

**Comment by 62442katieb** [comment]
Cool, I'll give it a shot. I thought I'd addressed that weirdness, oops!

**Comment by 62442katieb** [comment]
I'm pretty sure I got it. Someone take a look to confirm?

**Comment by Sharabesh** [comment]
Looks much better to me! I think we're good to close this issue.
